version: "2"

run:
  issues-exit-code: 1
  allow-parallel-runners: true
  allow-serial-runners: true
  concurrency: 32

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofumpt
